### ISSUE TITLE
stay up

### ISSUE THREAD

**Issue by ghost** [lovelysystems/lovely-pytest-docker#10]
hi
how can I prevent the docker container from stoping after running the test suite?
The goal is to avoid having to wait for the container to start each time I run tests

**Comment by Kaonael** [comment]
You can add flag --keepalive to Pytest config according to [this](https://github.com/lovelysystems/lovely-pytest-docker/blob/dc87ba3397223305db16a542cce123110ac93864/src/lovely/pytest/docker/compose.py#L201) line
