### ISSUE TITLE
allowing to stop containers

### ISSUE THREAD

**Issue by chicco785** [lovelysystems/lovely-pytest-docker#21]
for running test would be also good to be able to stop containers, not only to start them

**Comment by chicco785** [comment]
@dobe would this be relevant? happy to do a pr

**Comment by dobe** [comment]
> @dobe would this be relevant? happy to do a pr

hi @chicco785  that would be nice!  see the implementation of start https://github.com/lovelysystems/lovely-pytest-docker/blob/d4eb6951ab5b244d463ea161cd465343ba1538a7/src/lovely/pytest/docker/compose.py#L72-L77
