### ISSUE TITLE
Is lovely-pytest-docker v0.3.1 is compatible with python3.11

### ISSUE THREAD

**Issue by vivek-crest** [lovelysystems/lovely-pytest-docker#31]
The [Pypi documentation](https://pypi.org/project/lovely-pytest-docker/) mentions that lovely-pytest-docker v0.3.1 is compatible with Python 3.
Does this claim that the library is compatible with Python 3.11.x as well?
If not, is there a plan to release a Python 3.11.x compatible version?

**Comment by dobe** [comment]
hi, this should be compatible yes. if you have any issues, just create a ticket.
