### ISSUE TITLE
README says wait_for_service() accepts "check_service"

### ISSUE THREAD

**Issue by kahara** [lovelysystems/lovely-pytest-docker#8]
However, the actual name is [`check_server`](https://github.com/lovelysystems/lovely-pytest-docker/blob/master/src/lovely/pytest/docker/compose.py#L80).

**Comment by jukart** [comment]
fixed in https://github.com/lovelysystems/lovely-pytest-docker/commit/3340161eaa1cd755d4afb077d48a36423f7b827e

**Comment by kahara** [comment]
The text in README still says `check_service`.
